apiVersion: v1
kind: Namespace
metadata:
  name: management-ui 
  labels:
    role: management-ui 
---
apiVersion: v1
kind: Service
metadata:
  name: management-ui 
  namespace: management-ui 
spec:
  type: NodePort
  ports:
  - port: 80 
    targetPort: 9001
    nodePort: 32500
  selector:
    role: management-ui 
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: management-ui 
  namespace: management-ui 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: management-ui
        name: "management-ui"
    spec:
      containers:
      - name: management-ui 
        image: labdocker/star-collect:v0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9001