apiVersion: "v1"
kind: Pod
metadata:
  name: alpineweb
  annotations:
    container.apparmor.security.beta.kubernetes.io/alpineweb: localhost/restrict-apparmor
  namespace: namespace-psa
  labels:
    name: alpineweb
    owner: Praparn_L
    version: "1.0"
    module: WebServer
    environment: development
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
    - name: alpineweb
      image: labdocker/alpineweb:restrict
      resources:
        requests:
          memory: "16Mi"
          cpu: "100m"
        limits:
          memory: "32Mi"
          cpu: "200m"
      ports:
        - containerPort: 22
          protocol: TCP