apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-psp
  namespace: namespace-psp
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - psp-restricted