apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: security
  name: rolereadonly
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch"]