apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: security
  name: templaterolesubresource
rules:
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["testconfigmap"]
  verbs: ["update", "get"]