apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrolebindinglabsecurity
  namespace: security
subjects:
- kind: User
  name: labreadonly
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: templateclusterrole
  apiGroup: rbac.authorization.k8s.io