apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: rolebindingserviceaccountreadonly
 namespace: security
roleRef:
 kind: Role
 name: rolereadonly
 apiGroup: rbac.authorization.k8s.io
subjects:
— kind: ServiceAccount
  name: serviceaccount-readonly
  namespace: security