apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebindingserviceaccountreadonly
  namespace: security
subjects:
- kind: User
  name: labreadonly
  namespace: security
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: rolereadonly
  apiGroup: rbac.authorization.k8s.io