apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifest.yaml
- namespace.yaml

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
  patch: |-
    - op: remove
      path: /spec/replicas
